### PR TITLE
Update dependency versions a bit less

### PR DESCRIPTION
**Pull request by clhodapp**
* finagle: 6.33.0 -> 6.35.0
* scalacheck (for testing): 1.12.4 -> 1.13.2
* scalatest (for testing): 2.2.5 -> 3.0.0
* scala 2.11: 2.11.7 -> 2.11.8
* scala 2.10: 2.10.5 -> 2.10.6
* sbt: 0.13.8 -> 0.13.12

No source changes were needed.

### CODE REVIEW

**Comment by clhodapp** [comment]
Ping @vkostyukov

**Comment by vkostyukov** [comment]
Sorry for the delay @clhodapp! Looks good to me!

**Comment by vkostyukov** [comment]
Just published a release (0.1.7) including this PR. Thanks @clhodapp!

**Comment by clhodapp** [comment]
Great, thanks!

**Pull request merged**
